Answer questionnaire branch
tomozip/form pull request #9
Opened 2017-04-08 12:43 UTC by tomozip

アンケート回答フォーム機能を実装しました。
次は一旦前回のブランチの直しをしてからrubocop用のbranchを切ります。

2017-04-17 06:14 UTC, MihoSasaki commented
LGTM +1
あとは太田さんチェック！

2017-04-18 05:17 UTC, MihoSasaki commented
@tomozip これconflict解消してmasterから切り直しといてね！

2017-04-18 05:19 UTC, tomozip commented
今ローカルにmasterをpullしてconflictを解消しつつrebaseしています。
rebaseし終わったらもう一回pushしようと思います！

2017-04-19 04:20 UTC, NaotoOta commented
file diff 多ｗｗ

2017-04-19 05:20 UTC, NaotoOta requested changes

2017-04-19 05:20 UTC, NaotoOta commented on app/assets/javascripts/answers.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
消す

2017-04-19 05:20 UTC, NaotoOta commented on app/assets/javascripts/application.js
> +function answer_new() {
これはapplication.jsに書くものではなくない？

2017-04-19 05:20 UTC, NaotoOta commented on app/assets/javascripts/application.js
> +function answer_new() {
ってかそもそもanswer_newってなに？

2017-04-19 05:20 UTC, NaotoOta commented on app/assets/javascripts/application.js
> +    $('#normal').on('click', () => {
jsに関するclassは`js-`ってprefixつけるかなー

2017-04-19 05:20 UTC, NaotoOta commented on app/assets/javascripts/application.js
> +        lists.each((index, element) => {
listsって選択肢？
であればもっと簡単にできるはずradioかselectかにもよるけど

2017-04-19 05:20 UTC, NaotoOta commented on app/assets/stylesheets/answers.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
消す

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/answers_controller.rb
> +    que_answers = params.require(:answer)
あんま略さないほうが良いなーわかりにくくなる

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/answers_controller.rb
> +    que_answers = params.require(:answer)
あとrequireだけで使うとかはあんまない

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/answers_controller.rb
> +    if params[:temporary] # 一時保存なら
actionわけたほうが良いのでは？

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/answers_controller.rb
> +      que_answer = params.require(:answer).require(key.to_sym)
ここでもっかいrequireするなら上のcreateでする必要ない気がする。。。

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/answers_controller.rb
> +          next if index == 'category'
？？

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/answers_controller.rb
> +        value_isNull = que_answer[:body].empty?
value_isNullはcamelとsnakeまじってて気持ち悪い

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/answers_controller.rb
> +        unless value_isNull
return if value_isNull

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/answers_controller.rb
> +            answer_choice_params = que_answer[index].permit(:question_choice_id)
？？

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/companies_users_controller.rb
> +      @existsManager = true if companies_user.manager == 'delegate'
```
@existsManager = @companies_users.any? { |cu| cu.manager == 'delegate' }
```

cu.manager == 'delegate'
が何を指すかわからんけど、modelメソッドでも良いかも

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/companies_users_controller.rb
> +      @users.push(info: user, manager: companies_user.manager, companies_user_id: companies_user.id)
これは何？
userの配列ではないの？

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/questionnaires_controller.rb
>    def ajax_form
ajax_formというaction？

2017-04-19 05:20 UTC, NaotoOta commented on app/controllers/questionnaires_controller.rb
> +    render 'answers/questionnaire_list'
このrenderいる？

2017-04-19 05:20 UTC, NaotoOta commented
そもそもデータ構造を知りたいところ

2017-04-19 11:42 UTC, tomozip commented on app/assets/javascripts/application.js
> +function answer_new() {
すいません、answers.jsに移動しました。
answer_newではユーザー入力を検証して空白ならrequiredメッセージを出す処理をしていたんですが、命名が悪すぎたのでvalidate_user_inputに変更しました。

2017-04-19 11:58 UTC, tomozip commented on app/assets/javascripts/application.js
> +        lists.each((index, element) => {
listsは<input>か<textarea>か<select>かradioかcheckboxのどれかを含んだ<li>で、下のような構造になってます。
<li>
  <p>質問文</p>
  <input type="text">
</li>

2017-04-19 12:30 UTC, tomozip commented on app/controllers/answers_controller.rb
> +    if params[:temporary] # 一時保存なら
普通保存と一時保存用に二つ用意したsubmitボタンは同じformの内にあるので、結果的にaction先は一つになってしまうと思い同一action内で条件分岐させました。

2017-04-19 12:34 UTC, tomozip commented on app/controllers/answers_controller.rb
> +    que_answers = params.require(:answer)
editの方でnewと全く同じ処理をするのでプライベートメソッド化したのですが、その場合もメソッドにしないで二箇所に直書きしたほうがいいでしょうか？

2017-04-19 12:49 UTC, tomozip commented on app/controllers/answers_controller.rb
> +          next if index == 'category'
回答がチェックボックスの場合のパラメータを
```
{ category=>'checkbox', '0'=>id, '1'=>id }（選択されたcheckboxの値に設定していたidを０からのインデックスでハッシュに追加している）
```
というような構造にしたため、indexがcategoryの場合だけスキップしています。が、次のような構造にしたほうがいい気がして来ました。
```
{ category=>'checkbox', checked_choice_id=> {'0'=>id, '1'=>id} }
```

2017-04-19 13:57 UTC, tomozip commented on app/controllers/companies_users_controller.rb
> +      @users.push(info: user, manager: companies_user.manager, companies_user_id: companies_user.id)
usersテーブルの情報とcompanies_usersテーブルの情報(company_idとその人が代表者かどうか)を合わせた変数の配列にしてます。

2017-04-19 13:58 UTC, tomozip commented on app/controllers/questionnaires_controller.rb
>    def ajax_form
はい、ajaxのpost先用のアクションとして用意しました

2017-04-20 08:48 UTC, NaotoOta approved these changes

2017-04-20 08:48 UTC, merged